from pathlib import Path
import re
root=Path(__file__).resolve().parents[1]/'dist'
tr=(root/'index.html').read_text()
css=re.search(r'<style>(.*?)</style>',tr,re.S).group(1).replace('url("xp-wallpaper.png")','url("../xp-wallpaper.png")')
icon=re.search(r'<link rel="icon"[^>]+>',tr).group(0)
js=re.search(r'<script>(.*?)</script>',tr,re.S).group(1).replace("about:'Hakkımda',projects:'Projelerim',cv:'CV',skills:'Yetkinlikler',contact:'İletişim'", "about:'About',projects:'Projects',cv:'Résumé',skills:'Skills',contact:'Contact'").replace(' penceresini göster veya küçült',' window: show or minimize').replace("DateTimeFormat('tr-TR'", "DateTimeFormat('en-US'")
def controls(id,name,emoji):
 return f'''<div class="titlebar"><span class="mini">{emoji}</span><span class="title">{name}</span><div class="win-controls"><button data-min="{id}" aria-label="Minimize {name}">−</button><button data-max="{id}" aria-label="Maximize {name}">□</button><button data-close="{id}" aria-label="Close {name}">×</button></div></div><div class="toolbar">File &nbsp; Edit &nbsp; View &nbsp; Help</div>'''
projects=[('Java Security Fixer','java-security-fixer','A controlled workflow for Java static-analysis findings, CWE/OWASP context, secure file handling and reviewable fixes.','https://github.com/karligorkem/java-security-fixer','Java · Spring Boot · PostgreSQL'),('DB Optima','dboptima','A PostgreSQL index advisor that prioritizes candidates and uses measured before/after benchmarks for recommendations.','https://github.com/karligorkem/dboptima','Python · FastAPI · PostgreSQL'),('RAG Analysis','rag-analiz','A PDF analysis application with retrieval, reranking and page-level source references.','https://github.com/karligorkem/RAG-Analiz','FastAPI · Qdrant · RAG'),('Cloud Scheduler AI','cloud-scheduler-ai','A simulation comparing classic job placement strategies with masked reinforcement learning under server resource constraints.','https://github.com/karligorkem/cloud-scheduler-ai','Python · Gymnasium · pytest'),('Revenue Compass','gelir-pusulasi','A two-service daily revenue forecasting platform with CSV validation, model comparison and backtesting.','https://github.com/karligorkem/gelir-tahmin-platform','Spring Boot · FastAPI · AutoML'),('Truck Loading Optimization','tir-yukleme','A Streamlit prototype that rotates and places rectangular cargo and visualizes trailer volume use.',None,'Python · Streamlit · Optimization')]
items=''.join(f'''<article class="project"><div class="project-head"><h2>{name}</h2>{f'<a href="{repo}" target="_blank" rel="noopener noreferrer">Repository ↗</a>' if repo else ''}</div><p>{desc}</p><div class="project-links"><a href="projects/{slug}/">Read case study →</a></div><div class="tags">{''.join(f'<span class="tag">{x.strip()}</span>' for x in stack.split('·'))}</div></article>''' for name,slug,desc,repo,stack in projects)
html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#1853bb"><meta name="description" content="Görkem Karlı's backend, data and AI project portfolio in a Windows XP-inspired desktop."><title>Görkem Karlı | Portfolio</title>{icon}<style>{css}</style></head><body><a class="skip-link" href="#desktop-icons">Skip to desktop shortcuts</a><main class="desktop" id="desktop"><nav class="icons" id="desktop-icons" aria-label="Desktop shortcuts"><button class="icon" data-open="about"><span class="glyph" aria-hidden="true">👤</span>About</button><button class="icon" data-open="projects"><span class="glyph" aria-hidden="true">📁</span>Projects</button><button class="icon" data-open="cv"><span class="glyph" aria-hidden="true">📄</span>Résumé</button><button class="icon" data-open="skills"><span class="glyph" aria-hidden="true">⚙</span>Skills</button><button class="icon" data-open="contact"><span class="glyph" aria-hidden="true">✉</span>Contact</button></nav>
<aside class="welcome" aria-label="Portfolio introduction"><div class="welcome-head">Görkem Karlı · Portfolio</div><div class="welcome-body"><h1>Backend and data projects</h1><p>Explore my work, technical results and résumé through the desktop shortcuts.</p><div class="hero-actions"><button class="xp-button primary" data-open="projects">Open projects</button><button class="xp-button" data-open="cv">Open résumé</button><a class="xp-button" href="../Gorkem_Karli_CV.pdf" download>PDF résumé</a></div><p style="margin:10px 0 0"><a class="lang-link" href="../" lang="tr">Türkçe sürüm →</a></p></div></aside>
<section class="window" id="about" aria-label="About window" hidden>{controls('about','About Görkem Karlı','👤')}<div class="content"><p class="eyebrow">Computer engineering · Backend and data</p><h1>Görkem Karlı</h1><p class="lead">I build backend services, data workflows and machine learning applications with Java and Python.</p><p>My projects bring together data models, APIs, tests and measured outcomes. They include a PostgreSQL index advisor, a PDF research application with page-level sources and a job scheduling simulation.</p><p>I study Computer Engineering at Düzce University. During a software development internship, I contributed to a mobile application for production-floor issue reporting.</p><div class="hero-actions"><button class="xp-button primary" data-open="projects">Explore projects</button><button class="xp-button" data-open="cv">View résumé</button><a class="xp-button" href="https://github.com/karligorkem" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a class="xp-button" href="https://www.linkedin.com/in/g%C3%B6rkem-karl%C4%B1-56b181378/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div><p class="status">Open to software development opportunities in Istanbul and Ankara.</p></div></section>
<section class="window" id="projects" aria-label="Projects window" hidden>{controls('projects','Projects','📁')}<div class="content"><p class="eyebrow">Selected work</p><h1>Projects</h1><p>Security, database performance, document retrieval, forecasting and resource planning.</p><div class="project-list">{items}</div></div></section>
<section class="window" id="cv" aria-label="Résumé window" hidden>{controls('cv','Résumé','📄')}<div class="content"><p class="eyebrow">Résumé</p><h1>Görkem Karlı</h1><p class="lead">Computer Engineering student · Backend, Python and data applications</p><div class="hero-actions"><a class="xp-button primary" href="../Gorkem_Karli_CV.pdf" download>Download PDF résumé (Turkish)</a><a class="xp-button" href="mailto:gorkemkarli467@gmail.com">Email</a></div><h2>Profile</h2><p>Project experience in REST APIs with Java and Spring Boot, data-focused services with Python and FastAPI, PostgreSQL, Docker, testing, machine learning and retrieval-augmented applications.</p><h2>Education</h2><p><strong>Düzce University</strong> · BSc Computer Engineering (in progress)</p><h2>Experience</h2><p><strong>Sersim, Kayseri</strong> · Software Development Intern · 2024<br>Contributed to a React Native / Expo application for production-floor issue reporting, including barcode and QR scanning, photo reports, token-based API access and offline synchronization.</p><p><strong>Mondihome</strong> · Internship</p><h2>Selected projects</h2><p>Java Security Fixer · DB Optima · RAG Analysis · Cloud Scheduler AI · Revenue Compass</p><button class="xp-button" data-open="projects">View project details</button></div></section>
<section class="window" id="skills" aria-label="Skills window" hidden>{controls('skills','Skills','⚙')}<div class="content"><p class="eyebrow">Technical areas</p><h1>Skills</h1><div class="skill-grid"><div class="skill-box"><strong>Backend</strong><span>Java, Spring Boot, Python, FastAPI, REST APIs and OpenAPI.</span></div><div class="skill-box"><strong>Database</strong><span>PostgreSQL, SQLAlchemy, Alembic, query plans and index benchmarking.</span></div><div class="skill-box"><strong>Data and ML</strong><span>pandas, XGBoost, time-series features, backtesting, MAE and WAPE.</span></div><div class="skill-box"><strong>AI applications</strong><span>PDF processing, embedding retrieval, Qdrant, reranking and source-based RAG.</span></div><div class="skill-box"><strong>Testing and tools</strong><span>pytest, JUnit, Testcontainers, Git, Docker and Docker Compose.</span></div><div class="skill-box"><strong>Interfaces</strong><span>React Native / Expo and Streamlit visualizations.</span></div></div></div></section>
<section class="window" id="contact" aria-label="Contact window" hidden>{controls('contact','Contact','✉')}<div class="content"><p class="eyebrow">Contact</p><h1>Let's connect</h1><p>Contact me about backend, data, internships and software engineering roles in Istanbul or Ankara.</p><div class="contact-links"><a href="mailto:gorkemkarli467@gmail.com"><span>Email · gorkemkarli467@gmail.com</span><span>↗</span></a><a href="https://www.linkedin.com/in/g%C3%B6rkem-karl%C4%B1-56b181378/" target="_blank" rel="noopener noreferrer"><span>LinkedIn</span><span>↗</span></a><a href="https://github.com/karligorkem" target="_blank" rel="noopener noreferrer"><span>GitHub</span><span>↗</span></a></div></div></section>
<div class="start-menu" id="startMenu" hidden><div class="start-head">Görkem Karlı</div><button data-open="about">👤 &nbsp; About</button><button data-open="projects">📁 &nbsp; Projects</button><button data-open="cv">📄 &nbsp; Résumé</button><button data-open="skills">⚙ &nbsp; Skills</button><button data-open="contact">✉ &nbsp; Contact</button><a href="../Gorkem_Karli_CV.pdf" download>📄 &nbsp; PDF résumé</a><a href="../" lang="tr">🌐 &nbsp; Türkçe</a></div><footer class="taskbar"><button class="start" id="startButton" aria-expanded="false" aria-controls="startMenu"><span>✦</span> start</button><div class="task-items" id="taskItems"></div><div class="clock" id="clock" aria-label="Clock"></div></footer></main><script>{js}</script></body></html>'''
(root/'en').mkdir(exist_ok=True)
(root/'en'/'index.html').write_text(html)
print('Generated English desktop')
